#frontoffice
acme_core_homepage:
    path:     /
    defaults: { _controller: AcmeCoreBundle:Default:index }

acme_core_description:
    path:     /description
    defaults: { _controller: AcmeCoreBundle:Default:description }

acme_core_contactentreprise:
    path:     /contact/entreprise
    defaults: { _controller: AcmeCoreBundle:Default:contactEntreprise }

acme_core_feedback:
    path:     /contact/feedback
    defaults: { _controller: AcmeCoreBundle:Default:feedback }

acme_core_sponsor:
    path:     /sponsor
    defaults: { _controller: AcmeCoreBundle:Default:sponsor }

acme_core_inscription:
    path:     /contact/inscription
    defaults: { _controller: AcmeCoreBundle:Default:inscription }

acme_core_faq:
    path:     /faq
    defaults: { _controller: AcmeCoreBundle:Default:faq }

acme_core_modifResult:
    path:     /resultatContenu/{endroit}
    defaults: { _controller: AcmeCoreBundle:BackOffice:resultatContenu }

acme_core_contact:
    path:     /contact
    defaults: { _controller: AcmeCoreBundle:Default:contact }


#backoffice
acme_core_backoffice:
    path:     /admin/backoffice
    defaults: { _controller: AcmeCoreBundle:BackOffice:backoffice }

acme_core_logout:
    path:     /logout
    defaults: { _controller: AcmeCoreBundle:BackOffice:backoffice }

acme_core_feedbackuser:
    path:     /admin/feedbackuser
    defaults: { _controller: AcmeCoreBundle:BackOffice:feedbackuser }

acme_core_entreprise:
    path:     /admin/entreprise
    defaults: { _controller: AcmeCoreBundle:BackOffice:entreprise }

acme_core_inscrit:
    path:     /admin/inscrit
    defaults: { _controller: AcmeCoreBundle:BackOffice:inscrit }

acme_core_modif:
    path:     /admin/modif
    defaults: { _controller: AcmeCoreBundle:BackOffice:modif }



